config/routes.rb
FriendKarma::Application.routes.draw do

  resources :invitations

  get "/interested_user" => "interested_user#index", as: 'interested_users'
  post "/interested_user" => "interested_user#create", as: 'interested_user'

  resources :interested_user

  get "oauths/oauth"
  get "/dashboard" => "dashboard#index", as: 'dashboard'
  post "/dashboard" => "dashboard#destroy", as: 'dashboard'

  get "oauths/callback"

  resources :password_resets

  root to: 'interested_user#index'

  resources :users do

    member do
      get :activate
    end
  end

  resources :memberships

  resources :comments

  resources :requests

  get "/requests/:id/complete" => 'requests#completed_job', as: :completed_request
  get "/requests/:id/accepted" => 'requests#accepted', as: :request_accepted

  resources :jobs

  get "/jobs/:id/complete" => 'jobs#completed_job', as: :completed_job
  get "/jobs/:id/accepted" => 'jobs#accepted', as: :job_accepted

  resources :groups

  resources :user_sessions

  match 'login' => 'user_sessions#new', as: :login
  match 'logout' => 'user_sessions#destroy', as: :logout

  match "oauth/callback" => "oauths#callback"
  match "oauth/:provider" => "oauths#oauth", :as => :auth_at_provider

end

app/models/membership.rb
class Membership < ActiveRecord::Base
  attr_accessible :group_id, :user_id
  belongs_to :user
  belongs_to :group

  has_many :jobs
  has_many :comments
  has_many :requests
end

# == Schema Information
#
# Table name: memberships
#
#  id         :integer          not null, primary key
#  user_id    :integer
#  group_id   :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

app/controllers/memberships_controller.rb
class MembershipsController < ApplicationController
  # GET /memberships
  # GET /memberships.json
  before_filter :is_admin, except: [:create]
  def is_admin
    unless current_user.admin
      redirect_to root_path, notice: "Access Denied"
    end
  end
  def index
    @memberships = current_user.memberships

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @memberships }
    end
  end

  # GET /memberships/1
  # GET /memberships/1.json
  def show
    @membership = Membership.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @membership }
    end
  end

  # GET /memberships/new
  # GET /memberships/new.json
  def new
    @membership = Membership.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @membership }
    end
  end

  # GET /memberships/1/edit
  def edit
    @membership = Membership.find(params[:id])
  end

  # POST /memberships
  # POST /memberships.json
  def create
    @membership = Membership.new
    @membership.user_id = current_user.id
    @membership.group_id = params[:group_id]
    respond_to do |format|
      if @membership.save
        format.html { redirect_to group_path(@membership.group_id), notice: 'Membership was successfully created.' }
        format.json { render json: @membership, status: :created, location: @membership }
      else
        format.html { render action: root_path}
        format.json { render json: @membership.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /memberships/1
  # PUT /memberships/1.json
  def update
    @membership = Membership.find(params[:id])

    respond_to do |format|
      if @membership.update_attributes(params[:membership])
        format.html { redirect_to @membership, notice: 'Membership was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @membership.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /memberships/1
  # DELETE /memberships/1.json
  def destroy
    @membership = Membership.find(params[:id])
    @membership.destroy

    respond_to do |format|
      format.html { redirect_to memberships_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/memberships_helper.rb
module MembershipsHelper
end

app/views/memberships/_form.html.erb
<%= form_for(@membership) do |f| %>
  <% if @membership.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@membership.errors.count, "error") %> prohibited this membership from being saved:</h2>

      <ul>
      <% @membership.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :group_id %><br />
    <%= f.number_field :group_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/memberships/edit.html.erb
<h1>Editing membership</h1>

<%= render 'form' %>

<%= link_to 'Show', @membership %> |
<%= link_to 'Back', memberships_path %>

app/views/memberships/index.html.erb
<h1><%= current_user.username.capitalize %>'s Memberships</h1>

<p>*Leaving a group is permanent. Rejoining groups is only possible through a member invitation.*</p>

<table>
  <tr>
    <th>Groups</th>
    <th></th>
  </tr>

<% @memberships.each do |membership| %>
  <tr>
    <td><%= membership.group.name %></td>
    <td><%= link_to 'Leave Group', membership, method: :delete, data: { confirm: 'Are you sure?' } %></td>


  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Membership', new_membership_path %>

app/views/memberships/new.html.erb
<h1>New membership</h1>

<%= render 'form' %>

<%= link_to 'Back', memberships_path %>

app/views/memberships/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>User:</b>
  <%= @membership.user.username %>
</p>

<p>
  <b>Group:</b>
  <%= @membership.group.name %>
</p>


<%= link_to 'Edit', edit_membership_path(@membership) %> |
<%= link_to 'Back', memberships_path %>