config/routes.rb
FriendKarma::Application.routes.draw do

  resources :invitations

  get "/interested_user" => "interested_user#index", as: 'interested_users'
  post "/interested_user" => "interested_user#create", as: 'interested_user'

  resources :interested_user

  get "oauths/oauth"
  get "/dashboard" => "dashboard#index", as: 'dashboard'
  post "/dashboard" => "dashboard#destroy", as: 'dashboard'

  get "oauths/callback"

  resources :password_resets

  root to: 'interested_user#index'

  resources :users do

    member do
      get :activate
    end
  end

  resources :memberships

  resources :comments

  resources :requests

  get "/requests/:id/complete" => 'requests#completed_job', as: :completed_request
  get "/requests/:id/accepted" => 'requests#accepted', as: :request_accepted

  resources :jobs

  get "/jobs/:id/complete" => 'jobs#completed_job', as: :completed_job
  get "/jobs/:id/accepted" => 'jobs#accepted', as: :job_accepted

  resources :groups

  resources :user_sessions

  match 'login' => 'user_sessions#new', as: :login
  match 'logout' => 'user_sessions#destroy', as: :logout

  match "oauth/callback" => "oauths#callback"
  match "oauth/:provider" => "oauths#oauth", :as => :auth_at_provider

end

app/models/job.rb
class Job < ActiveRecord::Base
  include PublicActivity::Model
  tracked owner: ->(controller, model) { controller && controller.current_user}

  attr_accessible :friend_karma_value, :group_id, :membership_id, :name,  :asked, :accepted, :flaky, :completed, :duration

  belongs_to :group
  belongs_to :membership
  has_many :requests
  has_many :comments

  validates_presence_of :friend_karma_value, :group_id, :membership_id, :name, :duration

end

# == Schema Information
#
# Table name: jobs
#
#  id                 :integer          not null, primary key
#  name               :string(255)
#  friend_karma_value :integer
#  group_id           :integer
#  membership_id      :integer
#  created_at         :datetime         not null
#  updated_at         :datetime         not null
#  asked              :boolean
#  flaky              :boolean
#  accepted           :boolean
#  acceptor_id        :integer
#  completed          :boolean          default(FALSE)
#  duration           :integer
#

app/controllers/jobs_controller.rb
class JobsController < ApplicationController

  before_filter :is_user_or_admin, except: [:index, :new, :create, :completed_job]

  def is_user_or_admin
    unless (current_user.id == Job.find_by_id(params[:id].to_i).membership.user.id ) || (current_user.admin)
      redirect_to root_path, notice: "Access Denied"
    end
  end

  def is_admin
    unless current_user.admin
      redirect_to root_path, notice: "Access Denied"
    end
  end

  def index
    user_jobs = current_user.jobs
    @jobs = Job.where(id: current_user.jobs )

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @jobs }
    end
  end

  # GET /jobs/1
  # GET /jobs/1.json
  def show
    @job = Job.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @job }
    end
  end

  # GET /jobs/new
  # GET /jobs/new.json
  def new
    @job = Job.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @job }
    end
  end

  # GET /jobs/1/edit
  def edit
    @job = Job.find(params[:id])
  end

  # POST /jobs
  # POST /jobs.json
  def create
    @job = Job.new(params[:job])
    @job.friend_karma_value = 100
    @job.membership_id = Membership.where("user_id = ? AND group_id = ?", current_user.id, @job.group).first.id
    @job.accepted = false
    respond_to do |format|
      if @job.save
        @job.group.users.each do |user|
          if user != current_user
            JobsMailer.job_created(user, @job).deliver
          end
        end
        format.html { redirect_to dashboard_url, notice: 'Job was successfully created.' }
        format.json { render json: @job, status: :created, location: @job }
      else
        format.html { render action: "new" }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /jobs/1
  # PUT /jobs/1.json
  def update
    @job = Job.find(params[:id])

    respond_to do |format|
      if @job.update_attributes(params[:job])
        format.html { redirect_to dashboard_url, notice: 'Job was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /jobs/1
  # DELETE /jobs/1.json
  def destroy
    @job = Job.find(params[:id])
    @job.destroy
    @job.requests.each do |request|
      user = request.user

      if user != current_user
        JobsMailer.job_completed(user, @job).deliver
      end
    end

      respond_to do |format|
        format.html { redirect_to dashboard_url }
        format.json { head :no_content }
      end
  end

    def completed_job
      job = Job.find(params[:id])
      job.completed = true
  job.save
      if job.acceptor_id
  acceptor = User.find(job.acceptor_id)
  acceptor.favors_done += 1
  acceptor.save
  job.user.favors_received += 1
      end
      redirect_to dashboard_url, notice: "Job completed!"
    end

    def accepted
      job = Job.find(params[:id])
      job.acceptor_id = current_user.id
      job.accepted = true
      job.save

      redirect_to dashboard_url, notice: "Job accepted!"
    end
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/jobs/_form.html.erb
<%= form_for(@job) do |f| %>
  <% if @job.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@job.errors.count, "error") %> prohibited this job from being saved:</h2>

      <ul>
      <% @job.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.hidden_field :friend_karma_value %>
  </div>
  <div class="field">
    <%= f.label :time %><br />
    <%= f.datetime_select :time %>
  </div>
  <div class="field">
    <%= f.label :group_id %><br />
    <%= f.collection_select(:group_id, current_user.groups, :id, :name) %>
  </div>
  <div class="field">
    <%= f.hidden_field :membership_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/jobs/edit.html.erb
<h1>Editing job</h1>

<%= render 'form' %>

<%= link_to 'Show', @job %> |
<%= link_to 'Back', jobs_path %>

app/views/jobs/index.html.erb
<%= render 'layouts/navbar'%>
<div class="row-fluid">
  <div class="span5 offset1">
    <h1 id="header_font">Listing jobs</h1>
  </div>
</div>
<div class="row-fluid">
	<div class="tile span 10 offset1">
		<table class="table">
		  <thead>
		    <tr>
		      <th>Name</th>
		      <th>Friend karma value</th>
		      <th>Time</th>
		      <th>Group</th>
		      <th>Membership</th>
		      <th></th>
		      <th></th>
		      <th></th>
		    </tr>
		  </thead>
		<% @jobs.each do |job| %>
  
		  <tbody>
			  <tr>
			    <td><%= job.name %></td>
			    <td><%= job.friend_karma_value %></td>
			    <td><%= job.duration %> Hours</td>
			    <td><%= job.group.name %></td>
			    <td><%= job.membership.user.first %> <%= job.membership.user.last %></td>
			    <td><%= link_to 'Show', job %></td>
			    <td><%= link_to 'Edit', edit_job_path(job) %></td>
			    <td><%= link_to 'Destroy', job, method: :delete, data: { confirm: 'Are you sure?' } %></td>
			  </tr>
			</tbody>
		<% end %>
		</table>
	</div>
  </div>
<br />
<div class="row-fluid">
	<div class="tile span4 offset2">
		<%= link_to 'New Job', new_job_path %>
	</div>
</div>

app/views/jobs/new.html.erb
<h1>New job</h1>

<%= render 'form' %>

<%= link_to 'Back', jobs_path %>

app/views/jobs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @job.name %>
</p>

<p>
  <b>Friend karma value:</b>
  <%= @job.friend_karma_value %>
</p>

<p>
  <b>Time:</b>
  <%= @job.time %>
</p>

<p>
  <b>Group:</b>
  <%= @job.group_id %>
</p>

<p>
  <b>Membership:</b>
  <%= @job.membership_id %>
</p>

<%= link_to 'Make a request', new_request_path(job_id:  @job.id)%>
<%= link_to 'Make a comment', new_comment_path(job_id: @job.id)%>
<% if current_user.id == @job.membership.user.id%>
  <%= link_to 'Job Completed',completed_job_path(@job)%> | 
<% elsif @job.asked && ! @job.accepted %>
  <%= link_to 'Accept Job', job_accepted_path(@job)%>
<% end %>
<%= link_to 'Edit', edit_job_path(@job) %> |
<%= link_to 'Back', jobs_path %>