config/routes.rb
FriendKarma::Application.routes.draw do

  resources :invitations

  get "/interested_user" => "interested_user#index", as: 'interested_users'
  post "/interested_user" => "interested_user#create", as: 'interested_user'

  resources :interested_user

  get "oauths/oauth"
  get "/dashboard" => "dashboard#index", as: 'dashboard'
  post "/dashboard" => "dashboard#destroy", as: 'dashboard'

  get "oauths/callback"

  resources :password_resets

  root to: 'interested_user#index'

  resources :users do

    member do
      get :activate
    end
  end

  resources :memberships

  resources :comments

  resources :requests

  get "/requests/:id/complete" => 'requests#completed_job', as: :completed_request
  get "/requests/:id/accepted" => 'requests#accepted', as: :request_accepted

  resources :jobs

  get "/jobs/:id/complete" => 'jobs#completed_job', as: :completed_job
  get "/jobs/:id/accepted" => 'jobs#accepted', as: :job_accepted

  resources :groups

  resources :user_sessions

  match 'login' => 'user_sessions#new', as: :login
  match 'logout' => 'user_sessions#destroy', as: :logout

  match "oauth/callback" => "oauths#callback"
  match "oauth/:provider" => "oauths#oauth", :as => :auth_at_provider

end

app/models/group.rb
class Group < ActiveRecord::Base
  attr_accessible :name
  has_many :users, through: :memberships
  has_many :memberships
  has_many :jobs
  has_many :requests, through: :jobs
  has_many :comments, through: :jobs
  has_and_belongs_to_many :invitations

  validates_presence_of :name
end

# == Schema Information
#
# Table name: groups
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
 before_filter :is_user_or_admin, except: [:index, :new, :create]

  def is_user_or_admin
    users = Group.find_by_id(params[:id].to_i).users
    ids = []
    users.each do |user|
      ids << user.id
    end
    unless (ids.include?(current_user.id) || (current_user.admin))
      redirect_to root_path, notice: "Access Denied"
    end
  end


  def index
    @groups = current_user.groups

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @groups }
    end
  end

  # GET /groups/1
  # GET /groups/1.json
  def show
    @group = Group.find(params[:id])
    @membership = Membership.new
    @membership.group_id = params[:id]
    @invitation = Invitation.new
    @invitation.group_id = params[:id]

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @group }
    end
  end

  # GET /groups/new
  # GET /groups/new.json
  def new
    @group = Group.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @group }
    end
  end

  # GET /groups/1/edit
  def edit
    @group = Group.find(params[:id])
  end

  # POST /groups
  # POST /groups.json
  def create
    @group = Group.new(params[:group])

    respond_to do |format|
      if @group.save
        Membership.create({user_id: current_user.id, group_id: @group.id})
        format.html { redirect_to @group, notice: 'Group was successfully created.' }
        format.json { render json: @group, status: :created, location: @group }
      else
        format.html { render action: "new" }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /groups/1
  # PUT /groups/1.json
  def update
    @group = Group.find(params[:id])

    respond_to do |format|
      if @group.update_attributes(params[:group])
        format.html { redirect_to @group, notice: 'Group was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1
  # DELETE /groups/1.json
  def destroy
    @group = Group.find(params[:id])
    @group.destroy

    respond_to do |format|
      format.html { redirect_to groups_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_form.html.erb
<%= form_for(@group) do |f| %>
  <% if @group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@group.errors.count, "error") %> prohibited this group from being saved:</h2>

      <ul>
      <% @group.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/groups/edit.html.erb
<h1>Editing group</h1>

<%= render 'form' %>

<%= link_to 'Show', @group %> |
<%= link_to 'Back', groups_path %>

app/views/groups/index.html.erb
<%= render 'layouts/navbar'%>
<div class="row-fluid">
  <div class="span5 offset1">	
    <h1 id="header_font"><%= current_user.username %>'s Groups</h1>
  </div>
</div>
<div class="row-fluid">
	<div class="tile span6 offset1">
		<table>
		<% @groups.each do |group| %>
		    <tr>
		      <td><b><%= group.name %></b></td>
		    <table>
		      <tr><td><%= link_to 'Group Details', group %></td></tr>
		      <tr><td>Members: </td>
		          <td><% group.users.each do |groupuser| %>
		          <a><%= groupuser.username %>. </a>
		          <% end %>
		          </td>
		      </tr>
		      </tr>
		</table>
		<br />
		<% end %>
		</table>
	</div>
</div>
<br/>
<div class="row-fluid">
	<div class="tile span4 offset2">
	  <%= link_to 'New Group', new_group_path %>
	  <a href="/memberships?group_id=1" data-method="post" rel="nofollow">Join Group</a>
	</div>
</div>

app/views/groups/new.html.erb
<h1>New group</h1>

<%= render 'form' %>

<%= link_to 'Back', groups_path %>

app/views/groups/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <h1><%= @group.name %> Details</h1>
  <%= link_to 'Edit Membership', memberships_path %> |
<%= link_to 'Back', groups_path %>
</p>

<table>
  <tr>
    <th>Username</th>
    <th>Email</th>
    <th>First</th>
    <th>Last</th>
    <th>Phone</th>
    <th></th>
  </tr>

  <% @group.users.each do |groupuser| %>
  <tr>
    <td><%= groupuser.username %></td>
    <td><%= groupuser.email %></td>
    <td><%= groupuser.first %></td>
    <td><%= groupuser.last %></td>
    <td><%= groupuser.phone %></td>
    <td></td>
  </tr>
  <% end %>
</table>
<br />

<!-- Invite New User  -->

<br />
<br />
<b>Invite New User</b>
<br />
<br />

<%= form_for(@invitation) do |f| %>
  <% if @invitation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@invitation.errors.count, "error") %> prohibited this invitation from being saved:</h2>

      <ul>
      <% @invitation.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.hidden_field :group_id, :value => @group.id %>
  </div>
  <div class="field">
    <%= f.hidden_field :invitor_id, :value => current_user.id %>
  </div>
  <div class="field">
    <%= f.hidden_field :invitee_id, :value => nil %>
  </div>
  <div class="field">
    <%= f.label :invitee_email %><br />
    <%= f.text_field :invitee_email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/groups/working.html.erb
<h1><%= current_user.username %>'s Groups</h1>




  <% @groups.each do |group| %>
    <ul><b><%= link_to group.name, group %></b>
      <b>Members:</b>
       <% group.users.each do |groupuser| %>
          <li>
            <a><%= groupuser.username %>. </a>
          </li>
          <% end %>

<br />
</ul>
<% end %>

<br />

<%= link_to 'New Group', new_group_path %>