config/routes.rb
FriendKarma::Application.routes.draw do

  resources :invitations

  get "/interested_user" => "interested_user#index", as: 'interested_users'
  post "/interested_user" => "interested_user#create", as: 'interested_user'

  resources :interested_user

  get "oauths/oauth"
  get "/dashboard" => "dashboard#index", as: 'dashboard'
  post "/dashboard" => "dashboard#destroy", as: 'dashboard'

  get "oauths/callback"

  resources :password_resets

  root to: 'interested_user#index'

  resources :users do

    member do
      get :activate
    end
  end

  resources :memberships

  resources :comments

  resources :requests

  get "/requests/:id/complete" => 'requests#completed_job', as: :completed_request
  get "/requests/:id/accepted" => 'requests#accepted', as: :request_accepted

  resources :jobs

  get "/jobs/:id/complete" => 'jobs#completed_job', as: :completed_job
  get "/jobs/:id/accepted" => 'jobs#accepted', as: :job_accepted

  resources :groups

  resources :user_sessions

  match 'login' => 'user_sessions#new', as: :login
  match 'logout' => 'user_sessions#destroy', as: :logout

  match "oauth/callback" => "oauths#callback"
  match "oauth/:provider" => "oauths#oauth", :as => :auth_at_provider

end

app/models/request.rb
class Request < ActiveRecord::Base
  include PublicActivity::Model
  tracked owner: ->(controller, model) { controller && controller.current_user}
  attr_accessible :job_id, :request_text, :membership_id

  belongs_to :job
  belongs_to :membership

  validates_presence_of :job_id, :request_text, :membership_id

  def accepted?
    acceptor_id.present?
  end

end

# == Schema Information
#
# Table name: requests
#
#  id            :integer          not null, primary key
#  job_id        :integer
#  membership_id :integer
#  request_text  :text
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#  completed     :boolean          default(FALSE)
#  acceptor_id   :integer
#

app/controllers/requests_controller.rb
class RequestsController < ApplicationController

  # GET /requests
  # GET /requests.json
  def index
    @requests = Request.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @requests }
    end
  end

  # GET /requests/1
  # GET /requests/1.json
  def show
    @request = Request.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @request }
    end
  end

  # GET /requests/new
  # GET /requests/new.json
  def new
    @request = Request.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @request }
    end
  end

  # GET /requests/1/edit
  def edit
    @request = Request.find(params[:id])
  end

  # POST /requests
  # POST /requests.json
  def create
    @request = Request.new(params[:request])

    @request.job_id = params[:job_id]
    @request.membership_id = current_user.memberships.where(group_id: @request.job.group.id).first.id
    respond_to do |format|
      if @request.save
        RequestsMailer.request_made(current_user, @request.job, @request).deliver
       # SmsController.new.request_created(@request.job, @request)
        format.html { redirect_to dashboard_url, notice: 'Request was successfully created.' }
        format.json { render json: @request, status: :created, location: @request }
      else
        format.html { render action: "new" }
        format.json { render json: @request.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /requests/1
  # PUT /requests/1.json
  def update
    @request = Request.find(params[:id])

    respond_to do |format|
      if @request.update_attributes(params[:request])
        RequestsMailer.request_modified(current_user,@request.job,@request).deliver
        format.html { redirect_to dashboard_url, notice: 'Request was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @request.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /requests/1
  # DELETE /requests/1.json
  def destroy
    @request = Request.find(params[:id])
    RequestsMailer.request_deleted(current_user, @request.job, @request).deliver
    @request.destroy

    respond_to do |format|
      format.html { redirect_to dashboard_url }
      format.json { head :no_content }
    end
  end

    def accepted
      request = Request.find(params[:id])
      request.acceptor_id = current_user.id

      request.save

      redirect_to dashboard_url, notice: "Request accepted!"
    end


    # WAZZZZZUUPPP
	def completed_request
		request = Request.find(params[:id])
		request_owner = request.user
		request_owner.favors_received += 1
		request_owner.save
		request_doer = request.job.user
		request_doer.favors_done += 1
		request_doer.save
		request.completed = true
		request.save
		redirect_to dashboard_url, notice: "Request completed!"
	end
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/views/requests/_form.html.erb
<%= form_for(@request) do |f| %>
  <% if @request.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@request.errors.count, "error") %> prohibited this request from being saved:</h2>

      <ul>
      <% @request.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :job_id %><br />
    <%= f.number_field :job_id %>
  </div>
  <div class="field">
    <%= f.label :membership_id %><br />
    <%= f.number_field :membership_id %>
  </div>
  <div class="field">
    <%= f.label :request_text %><br />
    <%= f.text_area :request_text %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/requests/edit.html.erb
<h1>Editing request</h1>

<%= render 'form' %>

<%= link_to 'Show', @request %> |
<%= link_to 'Back', requests_path %>

app/views/requests/index.html.erb
<%= render 'layouts/navbar'%>
<div class="row-fluid">
  <div class="span5 offset1">
    <h1 id="header_font">Listing requests</h1>
  </div>
</div>

<div class="row-fluid">
	<div class="tile span 10 offset1">
		<table class="table">
		  <thead>
  			<tr>
			    <th>Job</th>
			    <th>User</th>
			    <th>Request text</th>
			    <th></th>
			    <th></th>
			    <th></th>
			  </tr>
			</thead>

			<% @requests.each do |request| %>
			<tbody>
			  <tr>
			    <td><%= request.job_id %></td>
			    <td><%= request.membership_id %></td>
			    <td><%= request.request_text %></td>
			    <td><%= link_to 'Show', request %></td>
			    <td><%= link_to 'Edit', edit_request_path(request) %></td>
			    <td><%= link_to 'Destroy', request, method: :delete, data: { confirm: 'Are you sure?' } %></td>
			  </tr>
			</tbody>			
		<% end %>
		</table>
	</div>
</div>

<br />
<div class="row-fluid">
	<div class="tile span4 offset2">
		<%= link_to 'New Request', new_request_path %>
	</div>
</div>

app/views/requests/new.html.erb
<h1>New request</h1>

<%= render 'form' %>

<%= link_to 'Back', requests_path %>

app/views/requests/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Job:</b>
  <%= @request.job_id %>
</p>

<p>
  <b>User:</b>
  <%= @request.membership_id %>
</p>

<p>
  <b>Request text:</b>
  <%= @request.request_text %>
</p>


<%= link_to 'Edit', edit_request_path(@request) %> |
<%= link_to 'Back', requests_path %>